language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew
 - ./gradlew check
 

install: ./gradlew setupDecompWorkspace -S
script: ./gradlew build -S

env:
  global:
   - secure: "g7OKjprx4KjiWuVu4zONYGFQYx0By0N2w6EjWP6hTzVnxV+UoRnc7JagRJkWkCVUcAilJ7LWIMq1N2KQNFDDVoGZkTwAsDQkWYw6g+nWYciDh5RfrjcmLRnGLtWVnXQEh22r2/Vt10p/1ww9k1He4d0CdnEqsuWGsfXjDw3YxNU="

addons:
  coverity_scan:
    project:
      name: "GRM-Group/Narutocraft-PL_Mod"
      description: "Build submitted via Travis CI"
    notification_email: narutocraft@gmail.com
    build_command_prepend: "./gradlew setupDecompWorkspace -S"
    build_command:   "./gradlew build -S"
    branch_pattern: coverity_scan