language: java
jdk:
  - openjdk7
  - oraclejdk7

before_install:
 - chmod +x gradlew

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

env:
 global:
   - secure: "ZU0ijB/2FBTHkCmit2G3vKAlTHsXhgk9MkBpsY0KpxMFQl3WLxKXoh6SAIE7Vt7voayjANaDX4M51DToyiSWlYEllu2ShOnNN2rrsouhAMpPzHN9r5mzjXbx44UmnnAaFo4DUa05xIwhMhzs4l17+DBNGVOVVoe/ziGilV097jk="

addons:
  coverity_scan:
    project:
      name: "GRM-Group/Narutocraft-PL_Mod"
    notification_email: mizyn24@gmail.com
    build_command_prepend: "./gradlew setupCIWorkspace -S"
    build_command: "./gradlew build -S"
    branch_pattern: coverity_scan
    
    
branches:
  only:
    -master
    -coverity-scan